version: '3'

services:
  wordpress:
    image: arm64v8/wordpress:latest
    platform: linux/arm64/v8
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress_data:/var/www/html
      - .:/var/www/html/wp-content/plugins/wp-security-hardening
    depends_on:
      - db
    entrypoint: |
      sh -c '
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        mv wp-cli.phar /usr/local/bin/wp
        docker-entrypoint.sh apache2-foreground
      '

  db:
    image: arm64v8/mysql:8.0
    platform: linux/arm64/v8
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: somewordpress
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
